global function SP_HUB_TIMESHIFT_AutoPrecache

void function SP_HUB_TIMESHIFT_AutoPrecache()
{
#if DEV
	#if SERVER
	SetAutoPrecacheVersion( 5 )
	// NPC spawners found:
	AP_NPCSpawnerFound( "npc_dropship", 14 )
	AP_NPCSpawnerFound( "npc_marvin", 20 )
	AP_NPCSpawnerFound( "npc_prowler", 29 )
	AP_NPCSpawnerFound( "npc_soldier", 91 )
	AP_NPCSpawnerFound( "npc_soldier_shield_captain", 3 )
	AP_NPCSpawnerFound( "npc_stalker", 39 )
	AP_NPCSpawnerFound( "npc_stalker_zombie_mossy", 38 )
	AP_NPCSpawnerFound( "npc_super_spectre", 5 )
	AP_NPCSpawnerFound( "npc_titan_ogre_minigun", 16 )
	#endif

	AP_PrecacheWeapon( "melee_pilot_emptyhanded", 1 )
	AP_PrecacheWeapon( "melee_titan_punch", 2 )
	AP_PrecacheWeapon( "melee_titan_punch_ion", 1 )
	AP_PrecacheWeapon( "melee_titan_punch_legion", 18 )
	AP_PrecacheWeapon( "melee_titan_punch_northstar", 1 )
	AP_PrecacheWeapon( "melee_titan_punch_scorch", 1 )
	AP_PrecacheWeapon( "melee_titan_punch_tone", 1 )
	AP_PrecacheWeapon( "melee_titan_sword", 1 )
	AP_PrecacheWeapon( "mp_ability_cloak", 1 )
	AP_PrecacheWeapon( "mp_titanability_ammo_swap", 18 )
	AP_PrecacheWeapon( "mp_titanability_basic_block", 1 )
	AP_PrecacheWeapon( "mp_titanability_gun_shield", 18 )
	AP_PrecacheWeapon( "mp_titanability_hover", 2 )
	AP_PrecacheWeapon( "mp_titanability_laser_trip", 1 )
	AP_PrecacheWeapon( "mp_titanability_particle_wall", 1 )
	AP_PrecacheWeapon( "mp_titanability_phase_dash", 1 )
	AP_PrecacheWeapon( "mp_titanability_power_shot", 18 )
	AP_PrecacheWeapon( "mp_titanability_slow_trap", 1 )
	AP_PrecacheWeapon( "mp_titanability_smoke", 1 )
	AP_PrecacheWeapon( "mp_titanability_sonar_pulse", 1 )
	AP_PrecacheWeapon( "mp_titanability_tether_trap", 1 )
	AP_PrecacheWeapon( "mp_titancore_amp_core", 1 )
	AP_PrecacheWeapon( "mp_titancore_flame_wave", 1 )
	AP_PrecacheWeapon( "mp_titancore_flight_core", 2 )
	AP_PrecacheWeapon( "mp_titancore_laser_cannon", 1 )
	AP_PrecacheWeapon( "mp_titancore_salvo_core", 1 )
	AP_PrecacheWeapon( "mp_titancore_shift_core", 1 )
	AP_PrecacheWeapon( "mp_titancore_siege_mode", 18 )
	AP_PrecacheWeapon( "mp_titanweapon_arc_wave", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_dumbfire_rockets", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_flame_wall", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_heat_shield", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_laser_lite", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_leadwall", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_meteor", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_particle_accelerator", 2 )
	AP_PrecacheWeapon( "mp_titanweapon_predator_cannon", 18 )
	AP_PrecacheWeapon( "mp_titanweapon_rocketeer_rocketstream", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_shoulder_rockets", 2 )
	AP_PrecacheWeapon( "mp_titanweapon_sniper", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_sticky_40mm", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_tracker_rockets", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_vortex_shield", 2 )
	AP_PrecacheWeapon( "mp_titanweapon_vortex_shield_ion", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_xo16_shorty", 1 )
	AP_PrecacheWeapon( "mp_weapon_autopistol", 1 )
	AP_PrecacheWeapon( "mp_weapon_car", 6 )
	AP_PrecacheWeapon( "mp_weapon_defender", 1 )
	AP_PrecacheWeapon( "mp_weapon_frag_grenade", 37 )
	AP_PrecacheWeapon( "mp_weapon_mastiff", 6 )
	AP_PrecacheWeapon( "mp_weapon_mgl", 25 )
	AP_PrecacheWeapon( "mp_weapon_r97", 31 )
	AP_PrecacheWeapon( "mp_weapon_rocket_launcher", 3 )
	AP_PrecacheWeapon( "mp_weapon_rspn101", 1 )
	AP_PrecacheWeapon( "mp_weapon_satchel", 1 )
	AP_PrecacheWeapon( "mp_weapon_semipistol", 1 )
	AP_PrecacheWeapon( "mp_weapon_shotgun", 3 )
	AP_PrecacheWeapon( "mp_weapon_sniper", 2 )
	AP_PrecacheWeapon( "mp_weapon_spectre_spawner", 1 )
	AP_PrecacheWeapon( "mp_weapon_super_spectre", 6 )
	AP_PrecacheWeapon( "mp_weapon_thermite_grenade", 27 )
	AP_PrecacheWeapon( "mp_weapon_vinson", 4 )
	AP_PrecacheWeapon( "mp_weapon_wingman", 3 )
	AP_PrecacheModel( $"models/creatures/prowler/r2_prowler.mdl" )
	AP_PrecacheModel( $"models/gibs/human_gibs.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib7_r_shin.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib8_l_thigh1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib8_l_thigh2.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib9_l_bicep1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_hatch_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_l_arm1_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_l_arm2_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_r_arm1_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_r_arm2_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/og_gib_hatch_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/og_gib_r_forarm_d.mdl" )
	AP_PrecacheModel( $"models/humans/grunts/imc_grunt_rifle.mdl" )
	AP_PrecacheModel( $"models/humans/grunts/imc_grunt_shield_captain.mdl" )
	AP_PrecacheModel( $"models/humans/grunts/mlt_grunt_rifle.mdl" )
	AP_PrecacheModel( $"models/humans/heroes/mlt_hero_jack.mdl" )
	AP_PrecacheModel( $"models/robots/drone_frag/drone_frag.mdl" )
	AP_PrecacheModel( $"models/robots/marvin/marvin.mdl" )
	AP_PrecacheModel( $"models/robots/stalker/robot_stalker.mdl" )
	AP_PrecacheModel( $"models/robots/stalker/robot_stalker_l_arm_gib.mdl" )
	AP_PrecacheModel( $"models/robots/stalker/robot_stalker_l_leg_gib.mdl" )
	AP_PrecacheModel( $"models/robots/stalker/robot_stalker_mossy.mdl" )
	AP_PrecacheModel( $"models/robots/stalker/robot_stalker_r_arm_gib.mdl" )
	AP_PrecacheModel( $"models/robots/stalker/robot_stalker_r_leg_gib.mdl" )
	AP_PrecacheModel( $"models/robots/super_spectre/super_spectre_left_arm.mdl" )
	AP_PrecacheModel( $"models/robots/super_spectre/super_spectre_left_leg.mdl" )
	AP_PrecacheModel( $"models/robots/super_spectre/super_spectre_right_arm.mdl" )
	AP_PrecacheModel( $"models/robots/super_spectre/super_spectre_right_leg.mdl" )
	AP_PrecacheModel( $"models/robots/super_spectre/super_spectre_v1.mdl" )
	AP_PrecacheModel( $"models/titans/buddy/titan_buddy.mdl" )
	AP_PrecacheModel( $"models/titans/heavy/sp_titan_heavy_deadbolt.mdl" )
	AP_PrecacheModel( $"models/titans/heavy/titan_heavy_rodeo_battery.mdl" )
	AP_PrecacheModel( $"models/vehicle/crow_dropship/crow_dropship.mdl" )
	AP_PrecacheModel( $"models/vehicle/goblin_dropship/goblin_dropship.mdl" )
	AP_PrecacheModel( $"models/weapons/arms/buddypov.mdl" )
	AP_PrecacheModel( $"models/weapons/arms/human_pov_cockpit.mdl" )
	AP_PrecacheModel( $"models/weapons/arms/pov_mlt_hero_jack.mdl" )
	AP_PrecacheModel( $"models/weapons/arms/pov_titan_medium_cockpit.mdl" )
#endif

#if !DEV

	PrecacheWeapon( "melee_pilot_emptyhanded" )
	PrecacheWeapon( "melee_titan_punch" )
	PrecacheWeapon( "melee_titan_punch_ion" )
	PrecacheWeapon( "melee_titan_punch_legion" )
	PrecacheWeapon( "melee_titan_punch_northstar" )
	PrecacheWeapon( "melee_titan_punch_scorch" )
	PrecacheWeapon( "melee_titan_punch_tone" )
	PrecacheWeapon( "melee_titan_sword" )
	PrecacheWeapon( "mp_ability_cloak" )
	PrecacheWeapon( "mp_titanability_ammo_swap" )
	PrecacheWeapon( "mp_titanability_basic_block" )
	PrecacheWeapon( "mp_titanability_gun_shield" )
	PrecacheWeapon( "mp_titanability_hover" )
	PrecacheWeapon( "mp_titanability_laser_trip" )
	PrecacheWeapon( "mp_titanability_particle_wall" )
	PrecacheWeapon( "mp_titanability_phase_dash" )
	PrecacheWeapon( "mp_titanability_power_shot" )
	PrecacheWeapon( "mp_titanability_slow_trap" )
	PrecacheWeapon( "mp_titanability_smoke" )
	PrecacheWeapon( "mp_titanability_sonar_pulse" )
	PrecacheWeapon( "mp_titanability_tether_trap" )
	PrecacheWeapon( "mp_titancore_amp_core" )
	PrecacheWeapon( "mp_titancore_flame_wave" )
	PrecacheWeapon( "mp_titancore_flight_core" )
	PrecacheWeapon( "mp_titancore_laser_cannon" )
	PrecacheWeapon( "mp_titancore_salvo_core" )
	PrecacheWeapon( "mp_titancore_shift_core" )
	PrecacheWeapon( "mp_titancore_siege_mode" )
	PrecacheWeapon( "mp_titanweapon_arc_wave" )
	PrecacheWeapon( "mp_titanweapon_dumbfire_rockets" )
	PrecacheWeapon( "mp_titanweapon_flame_wall" )
	PrecacheWeapon( "mp_titanweapon_heat_shield" )
	PrecacheWeapon( "mp_titanweapon_laser_lite" )
	PrecacheWeapon( "mp_titanweapon_leadwall" )
	PrecacheWeapon( "mp_titanweapon_meteor" )
	PrecacheWeapon( "mp_titanweapon_particle_accelerator" )
	PrecacheWeapon( "mp_titanweapon_predator_cannon" )
	PrecacheWeapon( "mp_titanweapon_rocketeer_rocketstream" )
	PrecacheWeapon( "mp_titanweapon_shoulder_rockets" )
	PrecacheWeapon( "mp_titanweapon_sniper" )
	PrecacheWeapon( "mp_titanweapon_sticky_40mm" )
	PrecacheWeapon( "mp_titanweapon_tracker_rockets" )
	PrecacheWeapon( "mp_titanweapon_vortex_shield" )
	PrecacheWeapon( "mp_titanweapon_vortex_shield_ion" )
	PrecacheWeapon( "mp_titanweapon_xo16_shorty" )
	PrecacheWeapon( "mp_weapon_autopistol" )
	PrecacheWeapon( "mp_weapon_car" )
	PrecacheWeapon( "mp_weapon_defender" )
	PrecacheWeapon( "mp_weapon_frag_grenade" )
	PrecacheWeapon( "mp_weapon_mastiff" )
	PrecacheWeapon( "mp_weapon_mgl" )
	PrecacheWeapon( "mp_weapon_r97" )
	PrecacheWeapon( "mp_weapon_rocket_launcher" )
	PrecacheWeapon( "mp_weapon_rspn101" )
	PrecacheWeapon( "mp_weapon_satchel" )
	PrecacheWeapon( "mp_weapon_semipistol" )
	PrecacheWeapon( "mp_weapon_shotgun" )
	PrecacheWeapon( "mp_weapon_sniper" )
	PrecacheWeapon( "mp_weapon_spectre_spawner" )
	PrecacheWeapon( "mp_weapon_super_spectre" )
	PrecacheWeapon( "mp_weapon_thermite_grenade" )
	PrecacheWeapon( "mp_weapon_vinson" )
	PrecacheWeapon( "mp_weapon_wingman" )
	PrecacheModel( $"models/creatures/prowler/r2_prowler.mdl" )
	PrecacheModel( $"models/gibs/human_gibs.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib7_r_shin.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib8_l_thigh1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib8_l_thigh2.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib9_l_bicep1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_hatch_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_l_arm1_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_l_arm2_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_r_arm1_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_r_arm2_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/og_gib_hatch_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/og_gib_r_forarm_d.mdl" )
	PrecacheModel( $"models/humans/grunts/imc_grunt_rifle.mdl" )
	PrecacheModel( $"models/humans/grunts/imc_grunt_shield_captain.mdl" )
	PrecacheModel( $"models/humans/grunts/mlt_grunt_rifle.mdl" )
	PrecacheModel( $"models/humans/heroes/mlt_hero_jack.mdl" )
	PrecacheModel( $"models/robots/drone_frag/drone_frag.mdl" )
	PrecacheModel( $"models/robots/marvin/marvin.mdl" )
	PrecacheModel( $"models/robots/stalker/robot_stalker.mdl" )
	PrecacheModel( $"models/robots/stalker/robot_stalker_l_arm_gib.mdl" )
	PrecacheModel( $"models/robots/stalker/robot_stalker_l_leg_gib.mdl" )
	PrecacheModel( $"models/robots/stalker/robot_stalker_mossy.mdl" )
	PrecacheModel( $"models/robots/stalker/robot_stalker_r_arm_gib.mdl" )
	PrecacheModel( $"models/robots/stalker/robot_stalker_r_leg_gib.mdl" )
	PrecacheModel( $"models/robots/super_spectre/super_spectre_left_arm.mdl" )
	PrecacheModel( $"models/robots/super_spectre/super_spectre_left_leg.mdl" )
	PrecacheModel( $"models/robots/super_spectre/super_spectre_right_arm.mdl" )
	PrecacheModel( $"models/robots/super_spectre/super_spectre_right_leg.mdl" )
	PrecacheModel( $"models/robots/super_spectre/super_spectre_v1.mdl" )
	PrecacheModel( $"models/titans/buddy/titan_buddy.mdl" )
	PrecacheModel( $"models/titans/heavy/sp_titan_heavy_deadbolt.mdl" )
	PrecacheModel( $"models/titans/heavy/titan_heavy_rodeo_battery.mdl" )
	PrecacheModel( $"models/vehicle/crow_dropship/crow_dropship.mdl" )
	PrecacheModel( $"models/vehicle/goblin_dropship/goblin_dropship.mdl" )
	PrecacheModel( $"models/weapons/arms/buddypov.mdl" )
	PrecacheModel( $"models/weapons/arms/human_pov_cockpit.mdl" )
	PrecacheModel( $"models/weapons/arms/pov_mlt_hero_jack.mdl" )
	PrecacheModel( $"models/weapons/arms/pov_titan_medium_cockpit.mdl" )
#endif

	#if CLIENT
	ClTitanOgre_Init( $"models/titans/heavy/sp_titan_heavy_deadbolt.mdl" )
	ClTitanBuddy_Init( $"models/titans/buddy/titan_buddy.mdl" )
	#endif
}

