global function SP_BOOMTOWN_END_AutoPrecache

void function SP_BOOMTOWN_END_AutoPrecache()
{
#if DEV
	#if SERVER
	SetAutoPrecacheVersion( 5 )
	// NPC spawners found:
	AP_NPCSpawnerFound( "npc_drone_worker", 6 )
	AP_NPCSpawnerFound( "npc_frag_drone", 8 )
	AP_NPCSpawnerFound( "npc_prowler", 30 )
	AP_NPCSpawnerFound( "npc_soldier", 25 )
	AP_NPCSpawnerFound( "npc_spectre", 11 )
	AP_NPCSpawnerFound( "npc_stalker_zombie", 3 )
	AP_NPCSpawnerFound( "npc_super_spectre", 4 )
	AP_NPCSpawnerFound( "npc_titan_atlas_tracker", 1 )
	AP_NPCSpawnerFound( "npc_titan_stryder_leadwall", 2 )
	AP_NPCSpawnerFound( "npc_titan_stryder_rocketeer", 1 )
	AP_NPCSpawnerFound( "npc_titan_stryder_sniper", 1 )
	#endif

	AP_PrecacheWeapon( "melee_pilot_emptyhanded", 1 )
	AP_PrecacheWeapon( "melee_titan_punch", 4 )
	AP_PrecacheWeapon( "melee_titan_punch_ion", 1 )
	AP_PrecacheWeapon( "melee_titan_punch_legion", 1 )
	AP_PrecacheWeapon( "melee_titan_punch_northstar", 3 )
	AP_PrecacheWeapon( "melee_titan_punch_scorch", 1 )
	AP_PrecacheWeapon( "melee_titan_punch_tone", 3 )
	AP_PrecacheWeapon( "melee_titan_sword", 4 )
	AP_PrecacheWeapon( "mp_ability_cloak", 1 )
	AP_PrecacheWeapon( "mp_titanability_ammo_swap", 1 )
	AP_PrecacheWeapon( "mp_titanability_basic_block", 4 )
	AP_PrecacheWeapon( "mp_titanability_gun_shield", 1 )
	AP_PrecacheWeapon( "mp_titanability_hover", 6 )
	AP_PrecacheWeapon( "mp_titanability_laser_trip", 1 )
	AP_PrecacheWeapon( "mp_titanability_particle_wall", 3 )
	AP_PrecacheWeapon( "mp_titanability_phase_dash", 4 )
	AP_PrecacheWeapon( "mp_titanability_power_shot", 1 )
	AP_PrecacheWeapon( "mp_titanability_slow_trap", 1 )
	AP_PrecacheWeapon( "mp_titanability_smoke", 1 )
	AP_PrecacheWeapon( "mp_titanability_sonar_pulse", 3 )
	AP_PrecacheWeapon( "mp_titanability_tether_trap", 3 )
	AP_PrecacheWeapon( "mp_titancore_amp_core", 1 )
	AP_PrecacheWeapon( "mp_titancore_flame_wave", 1 )
	AP_PrecacheWeapon( "mp_titancore_flight_core", 6 )
	AP_PrecacheWeapon( "mp_titancore_laser_cannon", 1 )
	AP_PrecacheWeapon( "mp_titancore_salvo_core", 3 )
	AP_PrecacheWeapon( "mp_titancore_shift_core", 4 )
	AP_PrecacheWeapon( "mp_titancore_siege_mode", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_arc_wave", 4 )
	AP_PrecacheWeapon( "mp_titanweapon_dumbfire_rockets", 3 )
	AP_PrecacheWeapon( "mp_titanweapon_flame_wall", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_heat_shield", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_laser_lite", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_leadwall", 4 )
	AP_PrecacheWeapon( "mp_titanweapon_meteor", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_particle_accelerator", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_predator_cannon", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_rocketeer_rocketstream", 3 )
	AP_PrecacheWeapon( "mp_titanweapon_shoulder_rockets", 4 )
	AP_PrecacheWeapon( "mp_titanweapon_sniper", 3 )
	AP_PrecacheWeapon( "mp_titanweapon_sticky_40mm", 3 )
	AP_PrecacheWeapon( "mp_titanweapon_tracker_rockets", 3 )
	AP_PrecacheWeapon( "mp_titanweapon_vortex_shield", 4 )
	AP_PrecacheWeapon( "mp_titanweapon_vortex_shield_ion", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_xo16_shorty", 1 )
	AP_PrecacheWeapon( "mp_weapon_defender", 1 )
	AP_PrecacheWeapon( "mp_weapon_esaw", 1 )
	AP_PrecacheWeapon( "mp_weapon_frag_grenade", 27 )
	AP_PrecacheWeapon( "mp_weapon_hemlok", 5 )
	AP_PrecacheWeapon( "mp_weapon_hemlok_smg", 2 )
	AP_PrecacheWeapon( "mp_weapon_lmg", 1 )
	AP_PrecacheWeapon( "mp_weapon_lstar", 1 )
	AP_PrecacheWeapon( "mp_weapon_mastiff", 1 )
	AP_PrecacheWeapon( "mp_weapon_mgl", 3 )
	AP_PrecacheWeapon( "mp_weapon_rocket_launcher", 2 )
	AP_PrecacheWeapon( "mp_weapon_semipistol", 2 )
	AP_PrecacheWeapon( "mp_weapon_shotgun", 2 )
	AP_PrecacheWeapon( "mp_weapon_shotgun_pistol", 1 )
	AP_PrecacheWeapon( "mp_weapon_sniper", 4 )
	AP_PrecacheWeapon( "mp_weapon_spectre_spawner", 1 )
	AP_PrecacheWeapon( "mp_weapon_super_spectre", 5 )
	AP_PrecacheWeapon( "mp_weapon_vinson", 1 )
	AP_PrecacheModel( $"models/creatures/prowler/r2_prowler.mdl" )
	AP_PrecacheModel( $"models/gibs/human_gibs.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib7_r_shin.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib8_l_thigh1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib8_l_thigh2.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib9_l_bicep1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_hatch_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_l_arm1_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_l_arm2_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_r_arm1_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_r_arm2_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib7_r_shin.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib8_l_thigh1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib8_l_thigh2.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib9_l_bicep1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib_hatch_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib_l_arm1_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib_l_arm2_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib_r_arm1_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib_r_arm2_d.mdl" )
	AP_PrecacheModel( $"models/humans/grunts/imc_grunt_rifle.mdl" )
	AP_PrecacheModel( $"models/humans/grunts/mlt_grunt_rifle.mdl" )
	AP_PrecacheModel( $"models/humans/heroes/imc_hero_ash.mdl" )
	AP_PrecacheModel( $"models/humans/heroes/mlt_hero_jack.mdl" )
	AP_PrecacheModel( $"models/robots/aerial_unmanned_worker/aerial_unmanned_worker.mdl" )
	AP_PrecacheModel( $"models/robots/drone_frag/drone_frag.mdl" )
	AP_PrecacheModel( $"models/robots/spectre/imc_spectre.mdl" )
	AP_PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_arm_l.mdl" )
	AP_PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_arm_r.mdl" )
	AP_PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_leg_l.mdl" )
	AP_PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_leg_r.mdl" )
	AP_PrecacheModel( $"models/robots/stalker/robot_stalker.mdl" )
	AP_PrecacheModel( $"models/robots/stalker/robot_stalker_l_arm_gib.mdl" )
	AP_PrecacheModel( $"models/robots/stalker/robot_stalker_l_leg_gib.mdl" )
	AP_PrecacheModel( $"models/robots/stalker/robot_stalker_r_arm_gib.mdl" )
	AP_PrecacheModel( $"models/robots/stalker/robot_stalker_r_leg_gib.mdl" )
	AP_PrecacheModel( $"models/robots/super_spectre/super_spectre_left_arm.mdl" )
	AP_PrecacheModel( $"models/robots/super_spectre/super_spectre_left_leg.mdl" )
	AP_PrecacheModel( $"models/robots/super_spectre/super_spectre_right_arm.mdl" )
	AP_PrecacheModel( $"models/robots/super_spectre/super_spectre_right_leg.mdl" )
	AP_PrecacheModel( $"models/robots/super_spectre/super_spectre_v1.mdl" )
	AP_PrecacheModel( $"models/titans/buddy/titan_buddy.mdl" )
	AP_PrecacheModel( $"models/titans/light/sp_titan_light_locust.mdl" )
	AP_PrecacheModel( $"models/titans/light/sp_titan_light_raptor.mdl" )
	AP_PrecacheModel( $"models/titans/light/titan_light_rodeo_battery.mdl" )
	AP_PrecacheModel( $"models/titans/medium/sp_titan_medium_wraith.mdl" )
	AP_PrecacheModel( $"models/titans/medium/titan_medium_rodeo_battery.mdl" )
	AP_PrecacheModel( $"models/weapons/arms/buddypov.mdl" )
	AP_PrecacheModel( $"models/weapons/arms/human_pov_cockpit.mdl" )
	AP_PrecacheModel( $"models/weapons/arms/pov_mlt_hero_jack.mdl" )
	AP_PrecacheModel( $"models/weapons/arms/pov_titan_medium_cockpit.mdl" )
#endif

#if !DEV

	PrecacheWeapon( "melee_pilot_emptyhanded" )
	PrecacheWeapon( "melee_titan_punch" )
	PrecacheWeapon( "melee_titan_punch_ion" )
	PrecacheWeapon( "melee_titan_punch_legion" )
	PrecacheWeapon( "melee_titan_punch_northstar" )
	PrecacheWeapon( "melee_titan_punch_scorch" )
	PrecacheWeapon( "melee_titan_punch_tone" )
	PrecacheWeapon( "melee_titan_sword" )
	PrecacheWeapon( "mp_ability_cloak" )
	PrecacheWeapon( "mp_titanability_ammo_swap" )
	PrecacheWeapon( "mp_titanability_basic_block" )
	PrecacheWeapon( "mp_titanability_gun_shield" )
	PrecacheWeapon( "mp_titanability_hover" )
	PrecacheWeapon( "mp_titanability_laser_trip" )
	PrecacheWeapon( "mp_titanability_particle_wall" )
	PrecacheWeapon( "mp_titanability_phase_dash" )
	PrecacheWeapon( "mp_titanability_power_shot" )
	PrecacheWeapon( "mp_titanability_slow_trap" )
	PrecacheWeapon( "mp_titanability_smoke" )
	PrecacheWeapon( "mp_titanability_sonar_pulse" )
	PrecacheWeapon( "mp_titanability_tether_trap" )
	PrecacheWeapon( "mp_titancore_amp_core" )
	PrecacheWeapon( "mp_titancore_flame_wave" )
	PrecacheWeapon( "mp_titancore_flight_core" )
	PrecacheWeapon( "mp_titancore_laser_cannon" )
	PrecacheWeapon( "mp_titancore_salvo_core" )
	PrecacheWeapon( "mp_titancore_shift_core" )
	PrecacheWeapon( "mp_titancore_siege_mode" )
	PrecacheWeapon( "mp_titanweapon_arc_wave" )
	PrecacheWeapon( "mp_titanweapon_dumbfire_rockets" )
	PrecacheWeapon( "mp_titanweapon_flame_wall" )
	PrecacheWeapon( "mp_titanweapon_heat_shield" )
	PrecacheWeapon( "mp_titanweapon_laser_lite" )
	PrecacheWeapon( "mp_titanweapon_leadwall" )
	PrecacheWeapon( "mp_titanweapon_meteor" )
	PrecacheWeapon( "mp_titanweapon_particle_accelerator" )
	PrecacheWeapon( "mp_titanweapon_predator_cannon" )
	PrecacheWeapon( "mp_titanweapon_rocketeer_rocketstream" )
	PrecacheWeapon( "mp_titanweapon_shoulder_rockets" )
	PrecacheWeapon( "mp_titanweapon_sniper" )
	PrecacheWeapon( "mp_titanweapon_sticky_40mm" )
	PrecacheWeapon( "mp_titanweapon_tracker_rockets" )
	PrecacheWeapon( "mp_titanweapon_vortex_shield" )
	PrecacheWeapon( "mp_titanweapon_vortex_shield_ion" )
	PrecacheWeapon( "mp_titanweapon_xo16_shorty" )
	PrecacheWeapon( "mp_weapon_defender" )
	PrecacheWeapon( "mp_weapon_esaw" )
	PrecacheWeapon( "mp_weapon_frag_grenade" )
	PrecacheWeapon( "mp_weapon_hemlok" )
	PrecacheWeapon( "mp_weapon_hemlok_smg" )
	PrecacheWeapon( "mp_weapon_lmg" )
	PrecacheWeapon( "mp_weapon_lstar" )
	PrecacheWeapon( "mp_weapon_mastiff" )
	PrecacheWeapon( "mp_weapon_mgl" )
	PrecacheWeapon( "mp_weapon_rocket_launcher" )
	PrecacheWeapon( "mp_weapon_semipistol" )
	PrecacheWeapon( "mp_weapon_shotgun" )
	PrecacheWeapon( "mp_weapon_shotgun_pistol" )
	PrecacheWeapon( "mp_weapon_sniper" )
	PrecacheWeapon( "mp_weapon_spectre_spawner" )
	PrecacheWeapon( "mp_weapon_super_spectre" )
	PrecacheWeapon( "mp_weapon_vinson" )
	PrecacheModel( $"models/creatures/prowler/r2_prowler.mdl" )
	PrecacheModel( $"models/gibs/human_gibs.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib7_r_shin.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib8_l_thigh1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib8_l_thigh2.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib9_l_bicep1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_hatch_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_l_arm1_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_l_arm2_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_r_arm1_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_r_arm2_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib7_r_shin.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib8_l_thigh1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib8_l_thigh2.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib9_l_bicep1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib_hatch_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib_l_arm1_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib_l_arm2_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib_r_arm1_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib_r_arm2_d.mdl" )
	PrecacheModel( $"models/humans/grunts/imc_grunt_rifle.mdl" )
	PrecacheModel( $"models/humans/grunts/mlt_grunt_rifle.mdl" )
	PrecacheModel( $"models/humans/heroes/imc_hero_ash.mdl" )
	PrecacheModel( $"models/humans/heroes/mlt_hero_jack.mdl" )
	PrecacheModel( $"models/robots/aerial_unmanned_worker/aerial_unmanned_worker.mdl" )
	PrecacheModel( $"models/robots/drone_frag/drone_frag.mdl" )
	PrecacheModel( $"models/robots/spectre/imc_spectre.mdl" )
	PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_arm_l.mdl" )
	PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_arm_r.mdl" )
	PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_leg_l.mdl" )
	PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_leg_r.mdl" )
	PrecacheModel( $"models/robots/stalker/robot_stalker.mdl" )
	PrecacheModel( $"models/robots/stalker/robot_stalker_l_arm_gib.mdl" )
	PrecacheModel( $"models/robots/stalker/robot_stalker_l_leg_gib.mdl" )
	PrecacheModel( $"models/robots/stalker/robot_stalker_r_arm_gib.mdl" )
	PrecacheModel( $"models/robots/stalker/robot_stalker_r_leg_gib.mdl" )
	PrecacheModel( $"models/robots/super_spectre/super_spectre_left_arm.mdl" )
	PrecacheModel( $"models/robots/super_spectre/super_spectre_left_leg.mdl" )
	PrecacheModel( $"models/robots/super_spectre/super_spectre_right_arm.mdl" )
	PrecacheModel( $"models/robots/super_spectre/super_spectre_right_leg.mdl" )
	PrecacheModel( $"models/robots/super_spectre/super_spectre_v1.mdl" )
	PrecacheModel( $"models/titans/buddy/titan_buddy.mdl" )
	PrecacheModel( $"models/titans/light/sp_titan_light_locust.mdl" )
	PrecacheModel( $"models/titans/light/sp_titan_light_raptor.mdl" )
	PrecacheModel( $"models/titans/light/titan_light_rodeo_battery.mdl" )
	PrecacheModel( $"models/titans/medium/sp_titan_medium_wraith.mdl" )
	PrecacheModel( $"models/titans/medium/titan_medium_rodeo_battery.mdl" )
	PrecacheModel( $"models/weapons/arms/buddypov.mdl" )
	PrecacheModel( $"models/weapons/arms/human_pov_cockpit.mdl" )
	PrecacheModel( $"models/weapons/arms/pov_mlt_hero_jack.mdl" )
	PrecacheModel( $"models/weapons/arms/pov_titan_medium_cockpit.mdl" )
#endif

	#if CLIENT
	ClTitanBuddy_Init( $"models/titans/buddy/titan_buddy.mdl" )
	ClTitanAtlas_Init( $"models/titans/medium/sp_titan_medium_wraith.mdl" )
	ClTitanStryder_Init( $"models/titans/light/sp_titan_light_locust.mdl" )
	ClTitanStryder_Init( $"models/titans/light/sp_titan_light_raptor.mdl" )
	#endif
}

